Repository OSAM-GoToDouble/2019_IoT_GoToDouble, pull requests merged in 2019-10, with the labels that each got.

#2 Update README.md
  webview/README.md
  webview/uploads/architecture.PNG
  webview/uploads/brainstorming.jpg
  webview/uploads/diagram.PNG
  webview/uploads/test.PNG
  webview/uploads/test1.PNG
  webview/uploads/test2.PNG
Labels: documentation

#5 MIT 라이센스 선언
  LICENSE.txt
Labels: documentation

#6 Radar.js 설정 업데이트
  radar/radar.css
  radar/radar.html
  radar/radar.js
Labels: enhancement

#9 radar.js와 프론트 어플리케이션을 django와 연결
  reference_radar/radar.css
  reference_radar/radar.html
  reference_radar/radar.js
  reference_radar/test/server.py
  webview/monitor/post_creator.py
  webview/monitor/static/monitor/radar.css
  webview/monitor/static/monitor/radar.js
  webview/monitor/templates/monitor/index.html
  webview/monitor/test.py
  webview/monitor/views.py
  webview/requirements.txt
  webview/webview/settings.py
Labels: enhancement

#10 fix views.py logic
  webview/monitor/views.py
Labels: bug

#11 두개의 레이더 사용 가능하도록 UI 구성 및 기능 구현
  webview/monitor/static/monitor/radar.js
Labels: enhancement

#13 Library 변경&Update README.md
  arduino/README.md
  arduino/libraries/SoftwareServo.zip
  arduino/main/main.ino
Labels: documentation, enhancement

#14 python script에서 DB에 접근할 수 있도록 변경
  webview/monitor/management/__init__.py
  webview/monitor/management/commands/__init__.py
  webview/monitor/management/commands/orm_test.py
Labels: enhancement

#17 Access django orm without running django server
  webview/monitor/directORM/__init__.py
  webview/monitor/directORM/directORM_test.py
  webview/monitor/management/commands/orm_test.py
Labels: enhancement

#16 레이더 2개가 정상적으로 출력될 수 있도록 버그 수정
  webview/monitor/static/monitor/radar.js
  webview/monitor/test/make_mockup.py
  webview/monitor/views.py
Labels: bug

#15 라즈베리파이-아두이노-센서 블루투스 통신구현
  arduino_raspi_connection/arduino/final.ino
  arduino_raspi_connection/arduino/send_signal.ino
  arduino_raspi_connection/raspi/connect.py
  arduino_raspi_connection/raspi/connect_2.py
Labels: enhancement

#18 Successful arduino-raspi-server connection!
  arduino/main/final.io
  webview/monitor/directORM/con_one.py
  webview/monitor/directORM/con_two.py
  webview/monitor/directORM/directORM_test.py
  webview/monitor/static/monitor/radar.js
Labels: bug, enhancement
